### ISSUE TITLE
Minor syntax errors

### ISSUE THREAD

**Issue by FrenzyExists** [albertocruz6/albertocruz6.github.io#1]
There's some minor syntax errors on the `About` section

![image](https://user-images.githubusercontent.com/47986470/113234704-c8092600-926f-11eb-93ed-632cc4661a42.png)

**Comment by albertocruz6** [comment]
Hey! Thanks for pointing that out. I will change that as soon as possible

**Comment by albertocruz6** [comment]
albertocruz6/albertocruz6.github.io@1fde63cabd6549200236198a88ae1f5abb291203
